spring.application.name=transaction-management

spring.datasource.url=jdbc:postgresql://localhost:5432/<YOUR DB>
spring.datasource.username=<YOUR USERNAME>
spring.datasource.password=<YOUR PASSWORD
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=<JWT SECRET>